name: Pipefy Automation
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Automation
      env:
        PIPEFY_TOKEN: ${{ secrets.PIPEFY_TOKEN }}
        PHASE_ID_ORIGEM: ${{ secrets.PHASE_ID_ORIGEM }}
        PHASE_ID_DESTINO: ${{ secrets.PHASE_ID_DESTINO }} 
        PIPE_ID_DESTINO: ${{ secrets.PIPE_ID_DESTINO }}
      run: python pipefy_automation.py

    - name: Upload history
      uses: actions/upload-artifact@v3
      with:
        name: cards-history
        path: cards_copiados.json
        if-no-files-found: ignore
